// <auto-generated />
namespace TimesheetReport.Core.Infrastructure.DAL.Migrations.UserContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModifyUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifyUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201612200330335_ModifyUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
